[package]
name = "wmfocus"
description = "Visually focus windows by label"
version = "1.1.6-alpha.0"
repository = "https://github.com/svenstaro/wmfocus"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = ["wm", "window", "manager", "i3"]
categories = ["command-line-utilities", "command-line-interface"]
edition = "2018"

[features]
i3 = ["swayipc"]

[dependencies]
cairo-sys-rs = "0.10"
css-color-parser = "0.1"
font-loader = "0.11"
swayipc = { git = "https://github.com/JayceFayne/swayipc-rs", optional = true }
itertools = "0.9"
log = "0.4"
pretty_env_logger = "0.4"
regex = "1.4"
structopt = "0.3"
xcb = "0.9"
xkbcommon = "0.4"

[dependencies.cairo-rs]
version = "0.9"
features = ["xcb"]

[dependencies.xcb-util]
version = "0.3"
features = ["keysyms"]

[dependencies.x11]
version = "2.18.2"
features = ["xlib"]

[profile.release]
lto = true
codegen-units = 1
